spring:
  application:
    name: transfer-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/transferdb
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

server:
  port: 8083

services:
  account: http://localhost:8082
  limit: http://localhost:8084
  workflow: http://localhost:8085
  core-banking: http://localhost:8086

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
      limitService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
      workflowService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50